services:
    maria-database:
        image: mariadb:10.11.2
        env_file: ./maria-database/.env
        environment:
            TZ: Asia/Tokyo
        ports:
            - '3306:3306'
        restart: always
        volumes:
            - ./maria-database/custom.cnf:/etc/mysql/conf.d/custom.cnf:ro

networks:
    default:
        name: shared-network
        driver: bridge
